config/routes.rb
Timetracker::Application.routes.draw do
  
  post '/calendar/filter', :to => 'calendar#set_filters', :as => 'filter_calendar'    
  get '/calendar/events', :to => 'calendar#events', :as => 'calendar_events'

  devise_for :admin_users, ActiveAdmin::Devise.config        
  ActiveAdmin.routes(self)
  
  devise_scope :admin_user do
    get '/logout', :to => 'active_admin/devise/sessions#destroy', :as => "destroy_admin_user_session"
    get '/login', :to => 'active_admin/devise/sessions#new', :as => "new_admin_user_session"
    post '/login', :to => 'active_admin/devise/sessions#create', :as => "create_admin_user_session"
  end
   
end

app/views/shared/_admin_footer.html.haml
#site_footer
	#footerNav
		%ul
			%li= link_to "Dashboard", dashboard_path
			%li |
			%li= link_to "Calendar", calendar_path
			%li |
			%li= link_to "Current Sprint", sprint_path
			%li |
			%li= link_to "Projects", projects_path
			%li |
			%li= link_to "My Account", profile_admin_users_path
			%li |
			%li= link_to "Logout", destroy_admin_user_session_path
		= form_tag switch_projects_path do
			= label_tag :id, "Switch Project:"
			= select_tag :id, options_from_collection_for_select(Project.active.accessible_by(current_ability).includes(:client).reorder("lower(clients.name) asc, lower(projects.name) asc"), :url, :switcher_name, (@project.url rescue nil)), onchange: "if ( $(this).val() != '' ) $(this).closest('form').submit();", prompt: "Choose Project..."

app/views/shared/_ipad_warning.html.haml
#ipad-warning-bar.noprint
	#ipad-warning-content
		Add this app to your iPad for better experience, by clicking 'Add to Home Screen' from toolbar.

app/views/shared/_sidebar.html.erb
<div class="sidebar right">
	<div class="widget contacts">		
		<h2>Contact Information</h2>
		<ul>
			<li>
				<strong>Email</strong>
				<p><a href="mailto:support@sprintapp.com">support@sprintapp.com</a></p>
			</li>
			<li>
				<strong>Location</strong>
				<p>
			Knoxville, TN 37912</p>
			<p><a target="_blank" href="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=+&amp;q=knoxville,+tn&amp;ie=UTF8&amp;hq=&amp;hnear=Knoxville,+Knox,+Tennessee&amp;t=m&amp;z=11&amp;vpsrc=0&amp;iwloc=A" class="link-btn">View Map</a></p>
			</li>
			<li>
				<strong>Other Holdings</strong>
				<p>
					<a target="_blank" href="http://www.matt-brewer.com">www.matt-brewer.com</a><br>
					<a target="_blank" href="http://www.tipcounterapp.com">www.tipcounterapp.com</a><br>
					<a target="_blank" href="http://www.macfanatic.net/blog">www.macfanatic.net</a><br>
				</p>
			</li>
		</ul>			
	</div>
</div>

app/views/shared/_timer.html.haml
- ticket_timer = TicketTimer.find(:first, conditions: { admin_user_id: current_admin_user.id })
- bar_class = ticket_timer.present? ? "" : "hidden"
#timer-bar(class=bar_class)
	#red-bar
	#timer-content
		= render "shared/timer_content", ticket_timer: ticket_timer

app/views/shared/_timer_content.html.haml
- if ticket_timer.present?
	%a(href="#{project_ticket_path(ticket_timer.project, ticket_timer.ticket)}" title="View ticket ##{ticket_timer.ticket.id}")
		== #{ticket_timer.ticket.display_name} - #{truncate(ticket_timer.ticket.name, length: 100)} - 
		%span(id="timer_text" data-update="#{ticket_time_ticket_path(ticket_timer.ticket, format: :js)}")= ticket_timer.readable_elapsed

app/views/shared/_user_statistics.html.haml
- @stats = { today: {}, this_week: {}, last_week: {}, this_month: {}, last_month: {}, this_year: {}}

- billable_scope = TicketComment.billable.created_by(user)
- @stats[:today][:billable] = billable_scope.today.sum(:time)
- @stats[:this_week][:billable] = billable_scope.this_week.sum(:time)
- @stats[:last_week][:billable] = billable_scope.last_week.sum(:time) 
- @stats[:this_month][:billable] = billable_scope.this_month.sum(:time) 
- @stats[:last_month][:billable] = billable_scope.last_month.sum(:time) 
- @stats[:this_year][:billable] = billable_scope.this_year.sum(:time) 

- worked_scope = TicketComment.created_by(user)
- @stats[:today][:worked] = worked_scope.today.sum(:time)
- @stats[:this_week][:worked] = worked_scope.this_week.sum(:time)
- @stats[:last_week][:worked] = worked_scope.last_week.sum(:time)
- @stats[:this_month][:worked] = worked_scope.this_month.sum(:time)
- @stats[:last_month][:worked] = worked_scope.last_month.sum(:time)
- @stats[:this_year][:worked] = worked_scope.this_year.sum(:time)

%table
	%thead
		%tr
			%th Time Period
			%th Billable Hours
			%th Hours Worked
	%tr
		%td(class="bold") Today
		%td= number_to_human @stats[:today][:billable]
		%td= number_to_human @stats[:today][:worked]
	%tr
		%td(class="bold") This Week
		%td= number_to_human @stats[:this_week][:billable]
		%td= number_to_human @stats[:this_week][:worked]
	%tr
		%td(class="bold") Last Week
		%td= number_to_human @stats[:last_week][:billable]
		%td= number_to_human @stats[:last_week][:worked]
	%tr
		%td(class="bold") This Month
		%td= number_to_human @stats[:this_month][:billable]
		%td= number_to_human @stats[:this_month][:worked]	
	%tr
		%td(class="bold") Last Month
		%td= number_to_human @stats[:last_month][:billable]
		%td= number_to_human @stats[:last_month][:worked]
	%tr
		%td(class="bold") This Year
		%td= number_to_human @stats[:this_year][:billable]
		%td= number_to_human @stats[:this_year][:worked]
		
%p
	%strong
		%em
			This information is for internal purposes only.

app/views/shared/_utility_navigation.html.haml
%p(id="utility_nav" class="header-item")
	= link_to(display_name(current_active_admin_user), profile_admin_users_path, title: "Edit My Profile")
	= link_to(I18n.t('active_admin.logout'), destroy_admin_user_session_path)