config/routes.rb
Timetracker::Application.routes.draw do
  
  post '/calendar/filter', :to => 'calendar#set_filters', :as => 'filter_calendar'    
  get '/calendar/events', :to => 'calendar#events', :as => 'calendar_events'

  devise_for :admin_users, ActiveAdmin::Devise.config        
  ActiveAdmin.routes(self)
  
  devise_scope :admin_user do
    get '/logout', :to => 'active_admin/devise/sessions#destroy', :as => "destroy_admin_user_session"
    get '/login', :to => 'active_admin/devise/sessions#new', :as => "new_admin_user_session"
    post '/login', :to => 'active_admin/devise/sessions#create', :as => "create_admin_user_session"
  end
   
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  has_paper_trail
  
  belongs_to :client
  belongs_to :product_owner, :class_name => "AdminUser", :foreign_key => :product_owner_id, :conditions => proc { ['role = ?', 'admin'] }
  has_and_belongs_to_many :members, :join_table => "members_projects", :association_foreign_key => :member_id, :class_name => "AdminUser"
  has_many :milestones, :dependent => :destroy, :order => "milestones.name asc"
  has_many :contacts, :through => :client
  has_many :tickets, dependent: :destroy
  has_many :project_files, dependent: :destroy
  
  scope :sorted, order("lower(projects.name) asc")
  scope :active, where("completed = ?", false)
  scope :closed, where("completed = ?", true)
  scope :recent, order('created_at desc, lower(projects.name) asc').limit(5)
  scope :owned_by, lambda { |owner| includes(:product_owner).where("admin_users.id = ?", owner.id).sorted }
  default_scope order("lower(projects.name) asc")
  
  validate :uniqueness_per_account, on: :create
  validates :number, presence: true, numericality: { integer_only: true, greater_than_or_equal_to: 0 }
  validates :name, :presence => true, :format => { :with => /\w+/, :message => "must contain letters" }
  validates :start_date, :presence => true
  validates :end_date, :date => { :after_or_equal_to => :start_date }, :allow_blank => true
  validates :product_owner_id, :client_id, :presence => true
  validates :client, :presence => true
  validates :hourly_rate, :presence => true, :numericality => { :greater_than_or_equal_to => 0 }
    
  delegate :name, :to => :client, :prefix => true, :allow_nil => true
  
  after_initialize :set_default_values
  before_validation :determine_hourly_rate
  
  acts_as_url :name, limit: 100
  
  def display_name
    "##{number} #{client_name}: #{name}"
  end
  
  def switcher_name
    "#{client_name}: #{name} (##{number})"
  end
  
  def safe_end_date
    end_date.humanize rescue 'N/A'
  end
  
  def actual_time
    tickets.sum(:actual_time)
  end
  
  def estimated_time
    tickets.sum(:estimated_time)
  end
  
  def completion_percent
    return 0 if tickets.count == 0
    ((tickets.closed.count.to_f / tickets.active.count.to_f) * 100).round
  end
  
  def desired_completion_percent
    return 0 if tickets.should_be_closed_by_now.count == 0
    ((tickets.closed.count.to_f / tickets.should_be_closed_by_now.count.to_f) * 100).round
  end
  
  def budget_completion_percent
    return 0 if estimated_time == 0
    ((actual_time.to_f / estimated_time.to_f) * 100).round
  end
  
  def budget_desired_completion_percent
    affected_tickets = tickets.should_be_closed_by_now
    desired_budgeted_hours = affected_tickets.sum(:estimated_time)
    budgeted_hours = affected_tickets.sum(:actual_time)
    return 0 if budgeted_hours == 0
    [((desired_budgeted_hours.to_f / budgeted_hours.to_f) * 100).round, 100].min
  end
  
  def billable_time
    tickets.billable.sum(:actual_time)
  end
  
  def non_billable_time
    actual_time - billable_time
  end
  
  def archive!
    self.update_attribute :completed, true
  end
  
  def unarchive!
    self.update_attribute :completed, false
  end
  
  def to_param
    url
  end
  
  protected 
    
    def set_default_values
      if new_record?
        self.start_date ||= Date.today
        self.number ||= (Project.maximum(:number) + 1 rescue 1)
      end
    end
    
    def determine_hourly_rate
      unless self.client.nil?
        self.hourly_rate ||= self.client.hourly_rate
      end
    end
    
    def uniqueness_per_account
      errors.add(:number, "this number is already in use") if Project.exists? number: number
    end
  
end

app/views/projects/_form.html.erb
<%=
semantic_form_for @project, :html => { :class => "filter_form consolidated_form" }, :builder => ActiveAdmin::FormBuilder do |f| 
  f.inputs "Project Information", :class => "inputs consolidated" do 
		f.input :number, as: :string, hint: "This is a unique number identifying the project for your records and is not editable after a project is created", input_html: { disabled: !@project.new_record? && @project.number.present? }
    f.input :name, hint: "The project number and client name will prefix this name wherever the project is used"
    f.input :start_date, :label => "Start Date", :as => :datepicker, :wrapper_html => { :class => "filter_form_field filter_date_range field-row" }
    f.input :end_date, :label => "End Date", :as => :datepicker, :wrapper_html => { :class => "filter_form_field filter_date_range field-row" }
		f.input :client, :wrapper_html => { :class => 'cleared' }, :collection => Client.all
		f.input :description, :input_html => { class: :ckeditor }
  end 
	f.inputs "Internal / Accounting" do
		f.input :hourly_rate, :hint => "All time assigned to tickets for this project will use this hourly rate. Defaults to the hourly rate dictated to for the client, if left empty.", label: "Hourly Rate", as: :string
		f.input :product_owner, :label => "Product Owner", :required => true, :collection => AdminUser.active.admin, hint: "The product owner is responsible for overseeing this project and will see this project on his/her dashboard."
	end
	f.inputs "Members" do
		f.input :members, :as => :check_boxes, :collection => AdminUser.active, hint: "Project members can access the project and all its resources and may be assigned tickets."
	end
  f.buttons 
end 
%>

app/views/projects/_members_sidebar.html.erb
<ul>
	<% resource.members.active.each do |member| %>
    <li><%= link_to member.full_name, admin_user_path(member) %></li>
  <% end %>
</ul>

app/views/projects/_project_information_sidebar.html.erb
<div class="attributes_table">
	<table cellpadding="0" cellspacing="0">
		<tr>
			<th>Tickets</th>
			<td><%= tickets.count %></td>
		</tr>
		<tr>
			<th>Milestones</th>
			<td><%= milestones.count %></td>
		</tr>
		<tr>
			<th>Estimated Hours</th>
			<td><%= number_to_human total_hours %></td>
		</tr>
		<tr>
			<th>Hours / Person</th>
			<% hours = (total_hours.to_f / num_assignees.to_f) rescue 0.0 %>
			<% hours = 0.0 if hours.nan? or hours.infinite? %>
			<td><span class="status <%= colorize_hours_per_team_member_for_sprint(hours) %>"><%= number_to_human(hours) %></span></td>
		</tr>
		<tr>
			<th>Tickets / Person</th>
			<% hours = (tickets.count.to_f / num_assignees) rescue 0.0 %>
			<% hours = 0.0 if hours.nan? or hours.infinite? %>
			<td><%= number_to_human(hours) %></td>
		</tr>
		<tr>
			<th>Team Members</th>
			<td><%= num_assignees %></td>
		</tr>
	</table>
</div>

app/views/projects/edit_whiteboard.html.erb
<%=
active_admin_form_for @project, url: save_whiteboard_project_path(@project) do |f|
	f.inputs "Project Whiteboard" do
		f.input :whiteboard, input_html: { class: "ckeditor" }, label: false
	end
	f.buttons
end
%>

app/views/projects/roadmap.html.erb
<div id="roadmap-budget-numbers">
	<% unless current_admin_user.employee? %>
	<h3><strong><%= number_to_currency @project.actual_time * @project.hourly_rate %> Actual / <%= number_to_currency @project.estimated_time * @project.hourly_rate %> Estimated</strong></h3>
	<% end %>
	
	<h3><strong><%= number_to_human((@project.end_date - Date.today).to_i) rescue 'Unknown # of' %> Days Left to Completion</strong></h3>
</div>
<div id="roadmap-title-info">
	<h2>Roadmap: <%= truncate @project.display_name, length: 30 %></h2>
	<h3><strong><%= @project.actual_time %> Actual / <%= @project.estimated_time %> Estimated / <%= @project.billable_time %> Billable</strong></h3>
</div>
<div class="cleared"></div>

<div class="project-milestone">
	<h3 class="milestone">Project Health</h3>
	
	<em>Ticket Progress</em>
	<%= project_progress_indicator(@project) %>
	<p><strong><%= @project.tickets.overdue.count %> Overdue / <%= @project.tickets.active.count %> Open / <%= @project.tickets.closed.count %> Closed</strong></p>
	
	<em>Budget Progress</em>
	<%= project_budget_progress_indicator(@project) %>
	<p><strong><%= @project.actual_time %> Actual / <%= @project.estimated_time %> Estimated</strong></p>
	
	<em>Billable vs Non-Billable</em>
	<%= billable_progress_indicator(@project) %>
	<p><strong><%= @project.billable_time %> Billable / <%= @project.non_billable_time %> Non-Billable / <%= @project.actual_time %> Total Time Spent</strong></p>
	
</div>

<% milestones = @project.milestones.overdue %>
<% unless milestones.count == 0 %>
	<h3>Overdue Milestones (<%= milestones.count %>)</h3>
	<%= content_tag 'table', :for => @project do %>
		<%= render :partial => "projects/roadmap/milestone", :collection => milestones  %>
	<% end %>
<% end %>

<% milestones = @project.milestones.active %>
<% unless milestones.count == 0 %>
	<h3>Open Milestones (<%= milestones.count %>)</h3>
	<%= content_tag 'table', :for => @project do %>
		<%= render :partial => "projects/roadmap/milestone", :collection => milestones  %>
	<% end %>
<% end %>

<% @project.milestones.each do |milestone| %>
	<div class="project-milestone">
		<h3 class="milestone"><%= milestone.name %> <%= '(%s)' % milestone.safe_end_date %></h3>
		<%= render :partial => 'milestones/roadmap/roadmap', :locals => { :milestone => milestone } %>
	</div>
<% end %>

app/views/projects/whiteboard.html.haml
.panel
	%h3== #{truncate @project.name, length: 75} Whiteboard
	.panel_contents
		.ticket-history-comment= raw @project.whiteboard
	
= form_tag edit_whiteboard_project_path(@project), method: :get do
	.buttons
		= submit_tag "Edit Whiteboard", class: :update